config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :mangas
      resources :comments
      resources :manga_categories
      resources :authors
      resources :categories
      resources :chapters
      resources :stats
      root to: "stats#index"
    end
  devise_for :users
  resources :mangas do 
    resources :chapters
    collection do
      post 'subcribe'
    end
  end
  resources :comments, only: :create
  resources :users, only: [:edit, :update, :index, :delete]
  post 'like', to: 'mangas#like', as: 'like'
  root 'mangas#index'
end

app/models/manga.rb
# frozen_string_literal: true

class Manga < ApplicationRecord
  enum status: { completed: 'completed', ongoing: 'ongoing' }
  has_many :chapters, -> { order(id: :asc) }
  has_many :comments
  has_many :likes
  belongs_to :author, optional: true
  has_many :manga_categories
  has_many :categories, through: :manga_categories
  has_many :subcribes
  has_many :users, through: :subcribes
  has_one_attached :cover

  validates :name, presence: true
  validates :views_count, presence: true
  validates :status, presence: true

  scope :date, -> { includes(:chapters).order('chapters.created_at desc') }
  scope :chap, lambda {
    left_joins(:chapters)
      .group(:id)
      .order('COUNT(chapters.id) DESC')
  }
  scope :find_name, -> { order(name: 'asc').includes(:chapters) }
end

app/controllers/admin/mangas_controller.rb
# frozen_string_literal: true

module Admin
  class MangasController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/mangas_controller.rb
# frozen_string_literal: true

class MangasController < ApplicationController
  before_action :set_locale

  def index
    @sort = params[:sort]
    @comments = Comment.last(7)
    return @mangas = Manga.all.includes(:chapters) if @sort.nil?

    if @sort == 'subcribe'
      return @mangas = current_user.mangas.includes(:chapters) if user_signed_in?

      return @mangas = Manga.none
    end
    @mangas = Manga.public_send params[:sort]
  end

  def show
    @manga = Manga.find(params[:id])
    view = @manga.views_count + 1
    @manga.update_attribute(:views_count, view)
    @comments = @manga.comments
    @comment = @manga.comments.build
  end

  def subcribe
    manga = Manga.find(params[:manga_id])
    if manga.users.exists? current_user.id
      current_user.subcribes.find(manga: manga).destroy
    else
      current_user.subcribes.create! manga: manga
      subcribe.destroy
    end
  end

  def like
    like = Like.find_like(params[:manga_id], params[:user_id]).first
    if like.nil?
      like = Like.new(manga_id: params[:manga_id], user_id: params[:user_id])
      like.save
    else
      like.destroy
    end
  end

  def set_locale
    I18n.locale = I18n.default_locale
  end
end

app/helpers/mangas_helper.rb
# frozen_string_literal: true

module MangasHelper
end

app/views/mangas/index.html.erb
<header class="header">
  <div class="container d-flex nav-header">
    <div class="nav-brand">
      <h3><%= t("index.title") %></h3>
    </div>
    <div class="nav-search d-flex">
      <input type="text" placeholder="Find manga..."/>
      <div class="search-btn">
        <i class="fa fa-search" aria-hidden="true"></i>
      </div>
    </div>
    <div>
      <% if user_signed_in? %>
        <%= image_tag current_user.avatar.attached? ? rails_blob_url(current_user.avatar, only_path: true) : 'anonymous.jpeg', class: 'user-ava' %>
        <%= link_to  current_user.name, edit_user_path(current_user.id) %>
        <%= link_to  "Log Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to  "Log In", new_user_session_path %>
        <%= link_to  "Sign Up", new_user_registration_path %>
      <% end %>
    </div>
  </div>
  <div class="container nav-menu">
    <button class="<%= 'btn-active' if @sort.nil? %>">
      <%= link_to root_path do %>
        <i class="fa fa-home" aria-hidden="true"></i>
      <% end %> 
    </button>
    <button class="<%= 'btn-active' if @sort == 'completed' %>">
      <%= link_to  "Đã Hoàn Thành", root_path(sort: 'completed') %>
    </button>
    <button class="<%= 'btn-active' if @sort == 'ongoing' %>">
      <%= link_to  "Đang Tiến Hành", root_path(sort: 'ongoing') %>
    </button>
    <button class="<%= 'btn-active' if @sort == 'find_name' %>">
      <%= link_to  "Xếp theo tên", root_path(sort: 'find_name') %> 
    </button>
    <button class="<%= 'btn-active' if @sort == 'date' %>">
      <%= link_to  "Xếp theo date", root_path(sort: 'date') %>
    </button>
    <button class="<%= 'btn-active' if @sort == 'chap' %>">
      <%= link_to  "Xếp theo số Chapter", root_path(sort: 'chap') %>
    </button>
    <button class="<%= 'btn-active' if @sort == 'subcribe' %>">
      <%= link_to  "Truyện Đang Theo Dõi", root_path(sort: 'subcribe') %>
    </button>
  </div>
</header>
<div class="container manga-body">
  <h4>NEW MANGA ></h4>
  <div class="owl-carousel">
    <% @mangas.each do |manga| %>
      <div class="slider-item">
        <%= link_to manga_path(manga.id) do %>
          <%= image_tag rails_blob_url(manga.cover, only_path: true), class: 'img-fluid' %>
        <% end %>
        <div class="slider-caption">
          <h5>
            <%= manga.name %>
          </h5>
          <p>
            Chapter <%= manga.chapters.first.name.split.last %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
  <h4>ALL MANGA ></h4>
  <div class="manga-container">
    <div class="manga-list">
      <% @mangas.each do |manga| %>
        <div class="manga-focus">
          <div class="manga-image">
            <%= link_to manga_path(manga.id) do %>
              <%= image_tag rails_blob_url(manga.cover, only_path: true), class: 'img-fluid' %>
            <% end %>
            <div class="manga-caption">
              <i class="fa fa-eye" aria-hidden="true"></i><%= manga.views_count%>
            </div>
          </div>
          <h5 class="manga-name">
            <%= manga.name %>
          </h5>
          <div class="manga-chapters">
            <% manga.chapters.first(3).each do |chap|%>
              <%= link_to  "Chapter #{chap.name.split.last}", manga_chapter_path(chap.manga_id ,chap.id) %>
              <br>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="manga-side">
      <div class="manga-sub">
        <h5>Truyện Đang Theo Dõi</h5>
        <p>Hướng dẫn theo dõi truyện</p>
      </div>
      <div class="manga-top">
        <div class="manga-top-options">
          <div class="manga-top-option top-month">
            TOP THÁNG
          </div>
          <div class="manga-top-option">
            TOP TUẦN
          </div>
          <div class="manga-top-option">
            TOP NGÀY
          </div>
        </div>
        <% @mangas.first(5).each.with_index do |manga, index| %>
          <div class="manga-top-list">
            <span class="manga-top-rank"><%= index + 1%></span>
            <div class="manga-top-info">
              <%= image_tag rails_blob_url(manga.cover, only_path: true), class: 'img-fluid' %>
              <div class="manga-top-specific">
                <h5><%= manga.name %></h5>
                <%= link_to  "Chapter #{manga.chapters.first.name.split.last}", manga_chapter_path(manga.id ,manga.chapters.first.id) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="manga-comments">
        <h5>New Comments</h5>
        <% @comments.each do |comment| %>
          <%= link_to  comment.manga.name, manga_path(comment.manga_id) %>
          <div class="manga-comment">
            <%= image_tag comment.user_id == 0 ? "anonymous.jpeg" : comment.user.avatar.attached? ? rails_blob_url(comment.user.avatar, only_path: true) : 'anonymous.jpeg', class: 'user-ava' %>
            <div class="manga-comment-info">
              <p><%= comment.user_id == 0 ? 'Anonymous' : comment.user.name %></p>
              <p><%= comment.content %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'carousel' %>

app/views/mangas/show.html.erb
<div class="manga-title">
  <%= @manga.name %>
  <h5>Cập nhật vào lúc <%= @manga.updated_at.localtime.strftime '%Y-%m-%d %H:%M:%S' %></h5>
</div>
<div class="manga-details">
  <div>
    <%= image_tag  rails_blob_url(@manga.cover, only_path: true) %>
  </div>
  <div class="manga-info">
    <h4>Tác Giả: <%= @manga.author_id.nil? ? '' : @manga.author.name %></h4>
    <h4>Tình Trạng: Đang tiến hành</h4>
    <h4>Thể loại: 
      <% @manga.manga_categories.includes(:category).each do |category| %>
         <%= category.category.name %>.
      <%end%>
    </h4>
    <h4>Lượt xem: <%= @manga.views_count %></h4>
    <% if user_signed_in? %>
      <%= form_tag( subcribe_mangas_path , remote: true) do %>
        <%= number_field_tag :manga_id , @manga.id , class: "hidden"  %>
        <%= number_field_tag :user_id , current_user.id , class: "hidden"  %>
        <%= submit_tag @manga.subcribes.find_by(user_id: current_user.id).nil? ? 'Subcribe' : 'Unsubcribe', class: "btn btn-primary", id: "subcribe-button" %>
      <% end %>
      <%= form_tag( like_path , remote: true) do %>
        <%= number_field_tag :manga_id , @manga.id , class: "hidden"  %>
        <%= number_field_tag :user_id , current_user.id , class: "hidden"  %>
        <%= submit_tag @manga.likes.find_by(user_id: current_user.id).nil? ? 'Like' : 'Unlike', class: "btn btn-primary", id: "like-button" %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="manga-description">
  <h3>Nội dung chính</h3>
  <p><%= @manga.description%></p>
</div>
<div class="manga-description">
  <h3>Danh sách chương</h3>
  <div class="chapter-list">
    <div class="chapter-focus">
      <h4>Số Chương</h4>
    </div>
    <% @manga.chapters.each do |chapter| %>
      <div class="chapter-focus chapter-details">
        <%= link_to  chapter.name, manga_chapter_path(chapter.manga_id ,chapter.id) %>
      </div>
    <% end %>
  </div>
  <h3>Bình Luận</h3>
  <div id="comment">
    <%= form_for @comment, remote: true do |f| %>
      <%= f.label :manga_id, @manga.id , class: "hidden"%>
      <%= f.number_field :manga_id , value: @manga.id , class: "hidden"  %>
      <%= f.label :user_id, "Bình Luận Với Tư Cách: "  %>
      <% if user_signed_in? %>      
        <%= f.select :user_id , [[current_user.name , current_user.id] , ["Anonymous" , 0]] , class: "form-control" %>
      <% else %>
        <%= f.select :user_id , [["Anonymous" , 0]] , class: "form-control" %>
      <% end %>
      <br>
      <%= f.label :content , 'Nội Dung'%>
      <br>
      <%= f.text_area :content, id: 'comment-text', data: { emojiable: true } %>
      <%= f.submit "Gửi", class: "btn btn-primary" %>
    <% end %>   
    <button id="emoji-trigger">Emoji</button>
  </div>
  <h3>Tất Cả Bình Luận</h3>
  <div id="comments">
    <%= render @comments%>
  </div>
</div>
<%= javascript_pack_tag 'emoji-picker' %>
<%= javascript_pack_tag 'subcribe' %>
<%= javascript_pack_tag 'like' %>

app/views/mangas/show.js.erb
import { EmojiButton } from '@joeattardi/emoji-button';

const picker = new EmojiButton();
const trigger = document.querySelector('#emoji-trigger');

picker.on('emoji', selection => {
  // handle the selected emoji here
  console.log(selection.emoji);
});

trigger.addEventListener('click', () => picker.togglePicker(trigger));